Repository Deducteam/Dedukti, pull requests merged in 2020-02, with the labels that each got.

#215 Implementation of debug flags as references
  api/env.ml
  api/processor.ml
  commands/dkcheck.ml
  commands/dkprune.ml
  kernel/basic.ml
  kernel/basic.mli
  kernel/confluence.ml
  kernel/confluence.mli
  kernel/dtree.ml
  kernel/dtree.mli
  kernel/matching.ml
  kernel/matching.mli
  kernel/reduction.ml
  kernel/reduction.mli
  kernel/signature.ml
  kernel/signature.mli
  kernel/typing.ml
  kernel/typing.mli
  parsing/scoping.ml
Labels: Dedukti 2.7

#214 Fixed exception naming
  api/env.ml
  api/env.mli
  api/errors.ml
  commands/dktop.ml
  kernel/basic.ml
  kernel/basic.mli
  kernel/confluence.ml
  kernel/confluence.mli
  kernel/dtree.ml
  kernel/dtree.mli
  kernel/reduction.ml
  kernel/rule.ml
  kernel/rule.mli
  kernel/signature.ml
  kernel/signature.mli
  kernel/typing.ml
  kernel/typing.mli
Labels: Dedukti 2.7, enhancement

#141 Private definitions
  README.md
  api/dep.ml
  api/env.ml
  api/env.mli
  api/errors.ml
  api/pp.ml
  api/processor.ml
  commands/dkprune.ml
  commands/dktop.ml
  kernel/signature.ml
  kernel/signature.mli
  parsing/entry.ml
  parsing/entry.mli
  parsing/lexer.mll
  parsing/menhir_parser.mly
  parsing/tokens.ml
  tests/KO/prv_fail_1.dk
  tests/KO/prv_fail_2.dk
  tests/LIB/prv.dk
  tests/scripts/IGNORE.sh
Labels: Dedukti 2.7

#99 Add a keyword to declare injective symbols
  README.md
  api/env.ml
  api/env.mli
  api/pp.ml
  kernel/signature.ml
  kernel/signature.mli
  kernel/typing.ml
  parsing/entry.ml
  parsing/lexer.mll
  parsing/menhir_parser.mly
  parsing/tokens.ml
Labels: Dedukti 2.7

#211 Cstr rec2
  api/env.ml
  commands/dkcheck.ml
  kernel/exsubst.ml
  kernel/exsubst.mli
  kernel/srcheck.ml
  kernel/srcheck.mli
  kernel/term.ml
  kernel/term.mli
  kernel/typing.ml
  tests/KO/church.dk
  tests/OK/SR_OK_1.dk
  tests/OK/SR_OK_2.dk
  tests/OK/SR_OK_3.dk
  tests/OK/SR_OK_4.dk
  tests/OK/WIP.dk
Labels: WIP, behaviour improvement
